hued: Responder Class Reference
Responder Class Reference
SSDP responder class.
Public Member Functions
Responder (io_service &io_service, const std::string &server, const std::string &service)
The constructor opens the UDP response port.
void update ()
Update the UUID of the HUE bridge.
void operator() (ip::address addr, uint16_t port, uint16_t mx)
Starts the SSID response.
Private Member Functions
void refresh (const boost::system::error_code &e)
Small helper to set the _refresh flag after the timeout t_refresh.
void respond (const boost::system::error_code &e, ip::address addr, uint16_t port)
Sends three response telegrams (see HUE_RESPONSE, HUE_ST1, HUE_ST2, HUE_ST3) to the endpoint given by addr and port.
Private Attributes
io_service & _io_service
std::string _server
std::string _service
std::string _uuid
ip::udp::socket _socket
bool _refresh
deadline_timer _trefresh
deadline_timer _tresponse
Detailed Description
SSDP responder class.
Definition at line 101 of file hued.cpp.
Member Function Documentation
operator()()
void Responder::operator() (ip::address addr, uint16_t port, uint16_t mx) inline
Starts the SSID response.
The function calls update() to get the current UUDI of the HUE bridge. Then it starts an async timer of between 0 and a (pseudo) random time given by mx (in seconds), which triggers respond(). This mechanism reduces the DDOS problem for the enumerating device when each enumerated device in the subnet answers to the same request.
Parameters
addr The address to respond to (HUE bridge)
port The port to respond to (HUE bridge)
mx An interval in seconds, in which the response should be sent.
Definition at line 218 of file hued.cpp.
References respond().
respond()
void Responder::respond (const boost::system::error_code & e, ip::address addr, uint16_t port) inline private
Sends three response telegrams (see HUE_RESPONSE, HUE_ST1, HUE_ST2, HUE_ST3) to the endpoint given by addr and port.
Parameters
e If this async timer error code says something other than OK the fuction returns immediately.
addr The address of the SSDP enumerator
port The port of the SSDP enumerator
Definition at line 245 of file hued.cpp.
References HUE_RESPONSE, HUE_ST1, HUE_ST2, and HUE_ST3.
Referenced by operator()().
update()
void Responder::update () inline
Update the UUID of the HUE bridge.
For obtaining the UUID of the HUE bridge this function downloads the description.xml from the bridge, parses this document and reads the UUID. The function immediately returns if it is called during t_refresh seconds after the last call to prevent DOS to the HUE bridge.
Definition at line 129 of file hued.cpp.
References refresh(), and t_refresh.
The documentation for this class was generated from the following file:
/home/as/Daten/src/hued/src/hued.cpp